### PR TITLE
fix: CRW-2971 use the same DEFAULT_OLM_SUGGESTED_NAMESPACE and DEFAULT_CHE_NAMESPACE == openshift-operators as in OperatorHub deployment; switch LEGACY_CHE_NAMESPACE from old workspaces to openshift-workspaces (3.x=3.1)

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

fix: CRW-2971 use the same DEFAULT_OLM_SUGGESTED_NAMESPACE and DEFAULT_CHE_NAMESPACE == openshift-operators as in OperatorHub deployment; switch LEGACY_CHE_NAMESPACE from old workspaces to openshift-workspaces (3.x=3.1)

Change-Id: Ia9d6cf98ae24c82e1b19fb3d03d8b514c34147f3
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-2971

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by RickJWagner** [comment]
lgtm
+1

**Comment by dmytro-ndp** [comment]
@nickboldt: there [README.md](https://github.com/redhat-developer/devspaces-chectl/blob/devspaces-3-rhel-8/README.md)  and [constants.ts](https://github.com/redhat-developer/devspaces-chectl/blob/devspaces-3-rhel-8/src/constants.ts#L43-L44) needed to be updated as well.

**Comment by nickboldt** [comment]
> @nickboldt: there [README.md](https://github.com/redhat-developer/devspaces-chectl/blob/devspaces-3-rhel-8/README.md) and [constants.ts](https://github.com/redhat-developer/devspaces-chectl/blob/devspaces-3-rhel-8/src/constants.ts#L43-L44) needed to be updated as well.

https://github.com/redhat-developer/devspaces-chectl/pull/100#issuecomment-1119830281

**Comment by dmytro-ndp** [comment]
Got it, thanks for explanation, Nick!

**Pull request merged**
