### PR TITLE
chore: Adapt upstream changes

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
Adapt upstream changes https://github.com/che-incubator/chectl/pull/2397

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-3353

### CODE REVIEW

**Review by nickboldt — COMMENTED** [review]
.

**Review by nickboldt — APPROVED** [review]
lots of changes! 

Seems OK, if you tested sync.sh locally...

**Comment by tolusha** [comment]
I've tested:
- sync.sh
- ./run server:deploy
- ./run server:deploy --olm-channel fast

**Comment by nickboldt** [comment]
> `./run server:deploy --olm-channel fast`

Does that install from https://quay.io/repository/devspaces/iib?tab=tags&tag=next or https://quay.io/repository/devspaces/iib?tab=tags&tag=latest (for the appropriate arch and OCP version) ? Both use `fast` channel...

**Comment by tolusha** [comment]
I use `quay.io/devspaces/iib:next-v${OPENSHIFT_VERSION}-${OPENSHIFT_ARCH}` CatalogSource Image

**Pull request merged**
